### ISSUE TITLE
Set Chrome as the default browser

### ISSUE THREAD

**Issue by bryankennedy** [boxen/puppet-chrome#11]
Has anyone ever seen a way to programmatically set Chrome as the default browser? I've been searching for a plist to modify but can't find much. If I get that sorted, it might be useful to include as an option in this module.

**Comment by JamshedVesuna** [comment]
+1 has this been done?

**Comment by bryankennedy** [comment]
I was able to do this in my personal manifest using:

    include chrome
    exec { 'Set Chrome as the default browser':
      command => 'open -n -a "Google Chrome" --args --make-default-browser',
      require => Class['chrome'],
    }

This still might be a nice thing to roll into the module as an option.

**Comment by jacobbednarz** [comment]
This module has been deprecated in favour of [Boxen's inbuilt support for Homebrew/Caskroom](https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17)
