### ISSUE TITLE
Chrome 28+, *.dev sites, and Asynchronous DNS Client

### ISSUE THREAD

**Issue by awirick** [boxen/puppet-chrome#9]
Chrome has had a built in Async DNS feature for some time, but seemed disabled by default. In 28+ default seems to mean enabled. This feature is causing all of our dev machines to not resolve *.dev domains through Dnsmasq. Unconfirmed theory:  Dnsmasq response is one of many async requests Chrome makes, and it is getting other DNS resolution first from "outside" sources.

This feature can be explicitly disabled via chrome://flags page:

![screen shot 2013-08-05 at 9 12 52 am](https://f.cloud.github.com/assets/219911/910375/25e7faaa-fdd9-11e2-8f88-d7b2d98e61f2.png)

Not sure of an automated resolution to this via puppet, but wanted to at least get the issue filed in case anyone else is seeing this.

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
